addSbtPlugin("io.spray"                  % "sbt-revolver"      % "0.9.1")
addSbtPlugin("org.foundweekends"         % "sbt-bintray"       % "0.5.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"      % "2.0.4")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"         % "1.3.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"      % "0.1.8")
